### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by seagoj** [ChantalMB/readable-ravelry#1]
Hello, I'd be happy to make pull requests for the known issues, but I haven't been able to reproduce them (at least not in firefox). Do you have any further information about what's wrong?

**Comment by ChantalMB** [comment]
Just checked it out, looks like it must have been an issue with some legacy code, because now that the website seems to have been updated the issues are no longer present! In the process of looking for the issues though, I discovered that as of yesterday that Ravelry has finally released an official dark mode, thus I will no longer be updating this project. 

Thank you so much for being willing to help though, I appreciate it!
